// Code generated by MockGen. DO NOT EDIT.
// Source: depthchart.go

// Package mock_framework is a generated GoMock package.
package mock_framework

import (
	reflect "reflect"

	framework "github.com/BinacsLee/escheduler/framework"
	gomock "github.com/golang/mock/gomock"
)

// MockDepthChart is a mock of DepthChart interface.
type MockDepthChart struct {
	ctrl     *gomock.Controller
	recorder *MockDepthChartMockRecorder
}

// MockDepthChartMockRecorder is the mock recorder for MockDepthChart.
type MockDepthChartMockRecorder struct {
	mock *MockDepthChart
}

// NewMockDepthChart creates a new mock instance.
func NewMockDepthChart(ctrl *gomock.Controller) *MockDepthChart {
	mock := &MockDepthChart{ctrl: ctrl}
	mock.recorder = &MockDepthChartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepthChart) EXPECT() *MockDepthChartMockRecorder {
	return m.recorder
}

// AddNode mocks base method.
func (m *MockDepthChart) AddNode(node framework.Node, depth int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddNode", node, depth)
}

// AddNode indicates an expected call of AddNode.
func (mr *MockDepthChartMockRecorder) AddNode(node, depth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNode", reflect.TypeOf((*MockDepthChart)(nil).AddNode), node, depth)
}

// DeleteNode mocks base method.
func (m *MockDepthChart) DeleteNode(node framework.Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteNode", node)
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockDepthChartMockRecorder) DeleteNode(node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockDepthChart)(nil).DeleteNode), node)
}

// GetMaxDepth mocks base method.
func (m *MockDepthChart) GetMaxDepth() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxDepth")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetMaxDepth indicates an expected call of GetMaxDepth.
func (mr *MockDepthChartMockRecorder) GetMaxDepth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxDepth", reflect.TypeOf((*MockDepthChart)(nil).GetMaxDepth))
}

// GetNodes mocks base method.
func (m *MockDepthChart) GetNodes(depth int64) framework.NodeSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes", depth)
	ret0, _ := ret[0].(framework.NodeSet)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockDepthChartMockRecorder) GetNodes(depth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockDepthChart)(nil).GetNodes), depth)
}

// Len mocks base method.
func (m *MockDepthChart) Len() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockDepthChartMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockDepthChart)(nil).Len))
}
